/:
  controller: general
  action: home

/login:
  controller: user
  action: login

/register:
  controller: user
  action: register

/accountUpdate:
  controller: user
  action: accountUpdate

/logout:
  controller: user
  action: logout

/valideAccount:
  controller: user
  action: valideAccount

/page404:
  controller: error
  action: page404

/page500:
  controller: error
  action: page500

/admin/dashboard:
  controller: admin
  action: dashboard

/admin/user:
  controller: admin
  action: user

/admin/role:
  controller: admin
  action: role

/admin/pageList:
  controller: admin
  action: pageList

/admin/pageTemplate:
  controller: admin
  action: pageTemplate

/admin/comment:
  controller: admin
  action: comment

/admin/visualSetting:
  controller: admin
  action: visualSetting

/admin/plugin:
  controller: admin
  action: plugin

/admin/globalSetting:
  controller: admin
  action: globalSetting


